- hosts: localhost
  connection: local
  gather_facts: false
#  collections:
#    - iac.foundation_service
  tasks:

  - name: debug info
    debug:
      msg: "Hola"

  - name: command
    command: ls /domotic-services
    register: salida

  - debug:
      var: salida
